"""add notification table

Revision ID: 33bc95ed646b
Revises: 119fbed96856
Create Date: 2020-07-09 17:53:13.288778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bc95ed646b'
down_revision = '119fbed96856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Notifications',
    sa.Column('N_ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=150), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('Timestamp', sa.Float(), nullable=True),
    sa.Column('Payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('N_ID')
    )
    op.create_index(op.f('ix_Notifications_Name'), 'Notifications', ['Name'], unique=False)
    op.create_index(op.f('ix_Notifications_Timestamp'), 'Notifications', ['Timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Notifications_Timestamp'), table_name='Notifications')
    op.drop_index(op.f('ix_Notifications_Name'), table_name='Notifications')
    op.drop_table('Notifications')
    # ### end Alembic commands ###
