"""users and posts table

Revision ID: 42a45d8dafbb
Revises: 
Create Date: 2020-07-03 00:41:05.741086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a45d8dafbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=150), nullable=False),
    sa.Column('Username', sa.String(length=15), nullable=False),
    sa.Column('Email', sa.String(length=120), nullable=False),
    sa.Column('Bio', sa.String(length=150), nullable=True),
    sa.Column('DateOfBirthday', sa.DateTime(), nullable=True),
    sa.Column('Gender', sa.String(length=30), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('Password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_index(op.f('ix_Users_Email'), 'Users', ['Email'], unique=True)
    op.create_index(op.f('ix_Users_Name'), 'Users', ['Name'], unique=False)
    op.create_index(op.f('ix_Users_Username'), 'Users', ['Username'], unique=True)
    op.create_table('Posts',
    sa.Column('PostID', sa.Integer(), nullable=False),
    sa.Column('Subject', sa.String(length=50), nullable=False),
    sa.Column('Body', sa.String(length=250), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('PostID')
    )
    op.create_index(op.f('ix_Posts_Timestamp'), 'Posts', ['Timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Posts_Timestamp'), table_name='Posts')
    op.drop_table('Posts')
    op.drop_index(op.f('ix_Users_Username'), table_name='Users')
    op.drop_index(op.f('ix_Users_Name'), table_name='Users')
    op.drop_index(op.f('ix_Users_Email'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
