"""posts table

Revision ID: 5b63cbd5ec9a
Revises: fe3182274e68
Create Date: 2020-06-29 19:40:04.062535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b63cbd5ec9a'
down_revision = 'fe3182274e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Posts',
    sa.Column('PostID', sa.Integer(), nullable=False),
    sa.Column('Subject', sa.String(length=50), nullable=True),
    sa.Column('Body', sa.String(length=250), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('PostID')
    )
    op.create_index(op.f('ix_Posts_Timestamp'), 'Posts', ['Timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Posts_Timestamp'), table_name='Posts')
    op.drop_table('Posts')
    # ### end Alembic commands ###
