"""add userposts table

Revision ID: 99247dd9525e
Revises: 42a45d8dafbb
Create Date: 2020-07-03 22:09:42.148772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99247dd9525e'
down_revision = '42a45d8dafbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserPosts',
    sa.Column('UserPostID', sa.Integer(), nullable=False),
    sa.Column('Body', sa.String(length=250), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['Users.UserID'], ),
    sa.PrimaryKeyConstraint('UserPostID')
    )
    op.create_index(op.f('ix_UserPosts_Timestamp'), 'UserPosts', ['Timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserPosts_Timestamp'), table_name='UserPosts')
    op.drop_table('UserPosts')
    # ### end Alembic commands ###
