"""remove contact email uniqueness

Revision ID: b6616bc04183
Revises: daa3b58672ff
Create Date: 2020-07-07 10:20:24.310290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6616bc04183'
down_revision = 'daa3b58672ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Contacts_Email', table_name='Contacts')
    op.create_index(op.f('ix_Contacts_Email'), 'Contacts', ['Email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Contacts_Email'), table_name='Contacts')
    op.create_index('ix_Contacts_Email', 'Contacts', ['Email'], unique=True)
    # ### end Alembic commands ###
