"""users table

Revision ID: fe3182274e68
Revises: 
Create Date: 2020-06-29 19:36:04.776543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3182274e68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=150), nullable=True),
    sa.Column('Username', sa.String(length=15), nullable=True),
    sa.Column('Email', sa.String(length=120), nullable=True),
    sa.Column('School', sa.String(length=250), nullable=True),
    sa.Column('Password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_index(op.f('ix_Users_Email'), 'Users', ['Email'], unique=True)
    op.create_index(op.f('ix_Users_Name'), 'Users', ['Name'], unique=False)
    op.create_index(op.f('ix_Users_School'), 'Users', ['School'], unique=False)
    op.create_index(op.f('ix_Users_Username'), 'Users', ['Username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_Username'), table_name='Users')
    op.drop_index(op.f('ix_Users_School'), table_name='Users')
    op.drop_index(op.f('ix_Users_Name'), table_name='Users')
    op.drop_index(op.f('ix_Users_Email'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
